<a href="https://colab.research.google.com/github/deepa22-eng/Machine-Learning-2026/blob/main/Deepa_Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Chemical Applications of Machine Learning (CHEM 4930/5610) - Spring 2026

### Assignment 3 - Deadline 2/27/2026
Points 10

#### General Comments
All figures and graph should have approriate labels on the two axis, and should include a legend with appropriate labels of the different plots.

The notebook should be return in working format. That is, I should be able to reset all the output and re-run all the cells and get the same results as you obtained.

**You should start by saving a copy of the notebook to your Google Drive so you preserve all changes.**

**Please add your name as a suffix to the filname**

**Student Name**: Deepa Ranabhat

**AI usage statement:**
I used Claude AI for understanding and interpretation of the code that I used to run the calculation.

### Task 1 - 10 points

In this task, we will consider data from this paper:
- Enhancing Permeability Prediction of Heterobifunctional Degraders Using Machine Learning and Metadynamics-Informed 3D Molecular Descriptors - [DOI:10.1021/acs.jcim.5c01600](https://doi.org/10.1021/acs.jcim.5c01600)

Where the authors consider the Permeability of so-called PROTAC compounds that are large and flexible molecules used in Targeted Protein Degradation.

All the dataset used in the paper, and the code use to obtain the results are given in this following Github repository:
- https://github.com/brykimjh/degrader-permeability-ml3d-metaD  

The specfic dataset that we use 32 PROTAC compounds with measured passive permeability (given in nm/s) and includes 17 2D features calculated by RDKit (see [here](https://github.com/brykimjh/degrader-permeability-ml3d-metaD/blob/main/data/calculate_2d_properties.py) for the script they are calculated), and 3 3D "ensemble" features that are obtained from molecular dynamics simulations as described in the paper.

The target value is the measured passive permeability that is experimentaly measured and given in nm/s.

The dataset can be seen here:
- https://github.com/brykimjh/degrader-permeability-ml3d-metaD/blob/main/outputs/ml_models/model_data.csv

Where the log10 transformed passive permeability is given by `P_appLog`. Note that here the passive permeability has been log transformed in based 10 using `np.log10`.

The 2D features obtained using RDKit are:
```
[
 'Molecular Weight (MW)', 'CharVol (characteristic volume)',
 'Flexibility (number of rotatable bonds / number of bonds)',
 'Number of Heavy Atoms (HA)', 'RingAtoms', 'Halogens', 'HeteroAtoms',
 'RotBonds (NRotB)', 'AllBonds', 'RingCount', 'NumStereo',
 'Fraction of sp3 Carbon Atoms (FSP3)', 'Hydrogen Bond Donors (HBD)',
 'Hydrogen Bond Acceptors (HBA)', 'cLogD^7.4',
 'Topological polar surface area (TPSA)',
 'Total non-polar surface area (TNSA)'
]
```
that includes various standard descriptors/features implemented in RDKit

and the 3D "ensemble" features obtained using MD simulations are
```
[
 'Ensemble_Average_PSA_Chloroform_ANI',
 'Ensemble_Average_Num_IMHB_Chloroform_ANI',
 'Ensemble_Average_RadiusOfGyration_Chloroform_ANI'
]
```
which inludes the average polar surface area (PSA), the average number of intramolecular hydrogen bonds (IMHB), and the average radius of gyration (that measures if the molecule is compact or extended).

#### A)
Split the dataset into compounds with two classes with low and high permeability evenly so each class has 16 compounds.

#### B)
For all 32 compounds, visualize the 2D chemical structure using RDKit and the mols2grid package, and show their measured passive permeability in nm/s and their low/high permeability classifciation.

#### C)
Perform classifcation using random forest classification model using the following hyperparameters:
- Number of tree: 100
- Maximum depth of each tree: 2
- Maximum number of features for each tree: 50% of the number of input features (rounded up if that number is a fraction)

You should perform the classification using 3 different feature set:
- 2D RDKit features
- 3D Ensemble features
- Combined set of 2D and 3D features

For each case, perform cross validation (CV) using a CV strategy of your choice, and obtain the average and standard deviation of metrics that measure the performance, including:
- Accuracy
- Precision
- Receiver Operating Characteristic Area Under the Curve (ROC AUC)  

In your analysis and metrics, the high permeability class should be consider as the postive class.

Based on your analysis, which feature set gives the best results for the classifcation?

#### D) - Optional for 2 points
Repeat your analysis from C) using a $k$ nearest neighbors classifer (i.e., $k$ nearest neighbors vote). Use the default value of 5 neighbors.

Do you obtain the same results as in C)?

In [106]:
# Bash script to download all the dataset. Don't worry if you don't understand it
%%bash

url="https://raw.githubusercontent.com/brykimjh/degrader-permeability-ml3d-metaD/refs/heads/main/outputs/ml_models/"
dataset_filename="model_data.csv"

rm -f ${dataset_filename}

wget ${url}/${dataset_filename} &> /dev/null

ls

2d_features.csv
model_data.csv
sample_data

In [107]:
# Bash script to download all the dataset. Don't worry if you don't understand it
%%bash

url="https://raw.githubusercontent.com/brykimjh/degrader-permeability-ml3d-metaD/refs/heads/main/outputs/ml_models/"
dataset_filename="model_data.csv"

rm -f ${dataset_filename}

wget ${url}/${dataset_filename} &> /dev/null

ls

2d_features.csv
model_data.csv
sample_data

In [108]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [109]:
dataset_1 = pd.read_csv("model_data.csv")
dataset_2 = pd.read_csv("2d_features.csv")

In [110]:
dataset_1

,Molecular Weight (MW),CharVol (characteristic volume),Flexibility (number of rotatable bonds / number of bonds),Number of Heavy Atoms (HA),RingAtoms,Halogens,HeteroAtoms,RotBonds (NRotB),AllBonds,RingCount,...,Fraction of sp3 Carbon Atoms (FSP3),Hydrogen Bond Donors (HBD),Hydrogen Bond Acceptors (HBA),cLogD^7.4,Topological polar surface area (TPSA),Total non-polar surface area (TNSA),Ensemble_Average_PSA_Chloroform_ANI,Ensemble_Average_Num_IMHB_Chloroform_ANI,Ensemble_Average_RadiusOfGyration_Chloroform_ANI,P_appLog
0,896.999,803.360,0.253521,65,42,0,19,18,71,7,...,0.456522,3,14,2.64400,209.98,710.02,193.71,0.97,5.68,1.491362
1,852.902,743.496,0.191176,62,42,0,19,13,68,7,...,0.395349,3,13,1.76390,217.82,642.18,252.14,0.87,5.24,1.049218
2,850.930,753.592,0.191176,62,42,0,18,13,68,7,...,0.409091,3,12,2.45750,208.59,671.41,248.01,0.67,5.47,0.812913
3,1020.210,896.016,0.276316,71,33,3,20,21,76,6,...,0.470588,3,12,7.70720,186.66,833.34,186.01,0.60,5.84,0.462398
4,1012.704,900.176,0.236842,70,39,1,20,18,76,7,...,0.460000,5,14,7.42946,214.98,785.02,105.63,2.92,5.60,-0.397940
5,837.830,697.696,0.265625,59,34,3,19,17,64,6,...,0.375000,1,12,4.40258,177.04,622.96,204.17,0.29,5.23,1.690196
6,1006.183,872.816,0.266667,70,33,3,20,20,75,6,...,0.460000,3,12,7.31710,186.66,813.34,175.16,0.32,5.41,1.136721
7,1128.150,931.232,0.256098,77,33,9,26,21,82,6,...,0.470588,3,12,8.44280,186.66,833.34,160.07,0.93,5.93,0.505150
8,1022.182,891.056,0.276316,71,33,3,21,21,76,6,...,0.460000,3,13,6.55350,195.89,804.11,197.66,1.64,5.16,1.235528
9,1078.143,902.096,0.253165,74,33,7,24,20,79,6,...,0.460000,3,12,7.80750,186.66,813.34,217.11,0.00,5.63,0.113943
10,722.847,661.968,0.275862,53,34,0,14,16,58,6,...,0.435897,3,11,4.25776,177.39,602.61,174.83,2.03,4.64,1.338456
11,917.851,766.648,0.277778,66,40,3,22,20,72,7,...,0.340909,4,15,4.37840,242.78,637.22,243.14,1.81,5.07,1.614897
12,1061.150,918.816,0.283951,75,39,3,23,23,81,7,...,0.423077,5,16,6.18942,241.76,798.24,155.46,3.16,5.39,1.371068
13,1024.529,890.672,0.337500,73,46,1,22,27,80,8,...,0.411765,6,16,5.25320,262.76,757.24,241.95,3.00,5.42,1.149219
14,788.349,695.408,0.092308,57,51,1,13,6,65,9,...,0.454545,1,9,5.36628,137.37,742.63,261.21,0.00,8.77,0.000000
15,1459.411,1291.704,0.236364,101,58,4,25,26,110,10,...,0.421053,2,13,12.29300,216.79,1303.21,119.69,2.38,6.70,-0.522879
16,775.826,669.592,0.136364,58,52,0,15,9,66,9,...,0.209302,3,12,5.35840,194.74,665.26,301.96,0.00,8.70,-1.000000
17,903.934,790.896,0.235294,62,39,2,17,16,68,7,...,0.444444,3,12,7.77536,177.07,722.93,149.92,2.01,4.97,0.949390
18,1008.039,880.352,0.293333,69,39,2,20,22,75,7,...,0.489796,3,15,6.96328,204.76,775.24,161.36,2.54,5.37,1.071882
19,1070.736,942.000,0.283951,74,44,1,21,23,81,8,...,0.471698,3,17,7.74180,217.65,842.35,145.60,2.24,5.33,0.944483
20,930.960,813.040,0.228571,64,39,2,18,16,70,7,...,0.434783,4,12,6.80128,196.94,723.06,134.68,3.02,5.20,0.826075
21,991.012,861.040,0.270270,68,39,2,20,20,74,7,...,0.458333,4,14,6.05428,215.40,744.60,137.19,3.90,5.60,0.778151
22,1035.065,905.000,0.298701,71,39,2,21,23,77,7,...,0.480000,4,15,6.07088,224.63,775.37,132.52,2.23,5.94,0.672098
23,993.657,871.816,0.223684,69,44,1,19,17,76,8,...,0.420000,4,14,7.57980,209.83,790.17,134.46,3.97,5.43,0.602060
24,1053.709,924.808,0.262500,73,44,1,21,21,80,8,...,0.442308,4,16,6.83280,228.29,811.71,201.37,2.62,5.71,0.591065
25,1097.762,961.800,0.289157,76,44,1,22,24,83,8,...,0.462963,4,17,6.84940,237.52,842.48,189.50,3.83,5.28,0.579784
26,1050.705,921.320,0.250000,73,44,1,20,20,80,8,...,0.433962,3,16,7.40608,208.42,851.58,170.24,2.48,5.45,0.863323
27,890.458,768.752,0.231884,62,46,3,18,16,69,8,...,0.454545,3,11,6.59200,156.10,723.90,139.42,2.00,5.13,0.531479
28,1019.711,903.008,0.233766,70,43,2,20,18,77,8,...,0.540000,5,14,6.69692,194.25,805.75,174.10,3.00,5.32,1.012837
29,962.069,832.720,0.270270,68,41,3,22,20,74,7,...,0.413043,5,14,4.94890,218.38,701.62,226.08,1.06,5.65,0.505150
30,823.311,712.712,0.215385,59,41,1,18,14,65,7,...,0.317073,5,13,4.31760,207.30,612.70,192.67,3.93,5.25,1.409933
31,1002.661,881.352,0.266667,69,39,1,20,20,75,7,...,0.469388,4,15,5.59668,211.49,768.51,131.56,2.00,5.32,0.995635

In [111]:
dataset_2

,Index,Compound,Smiles,P_app AB (nm/s),P_app BA (nm/s),P_app,Molecular Weight (MW),CharVol (characteristic volume),Flexibility (number of rotatable bonds / number of bonds),Number of Heavy Atoms (HA),...,RotBonds (NRotB),AllBonds,RingCount,NumStereo,Fraction of sp3 Carbon Atoms (FSP3),Hydrogen Bond Donors (HBD),Hydrogen Bond Acceptors (HBA),cLogD^7.4,Topological polar surface area (TPSA),Total non-polar surface area (TNSA)
0,1,6a,O=C(C(N1C(C2=CC=CC(NCCOCCOCCOCCC(N(CC3)CCN3C(C...,2.6,370,31.016125,896.999,803.360,0.253521,65.0,...,18.0,71.0,7.0,2.0,0.456522,3.0,14.0,2.64400,209.98,710.02
1,2,6b,O=C(C(N1C(C2=CC=CC(NC(COCCOCC(N(CC3)CCN3C(C=C4...,1.3,96,11.171392,852.902,743.496,0.191176,62.0,...,13.0,68.0,7.0,2.0,0.395349,3.0,13.0,1.76390,217.82,642.18
2,3,6c,O=C(C(N1C(C2=CC=CC(OCC(NCCCCC(N(CC3)CCN3C(C=C4...,1.0,42,6.480741,850.930,753.592,0.191176,62.0,...,13.0,68.0,7.0,2.0,0.409091,3.0,12.0,2.45750,208.59,671.41
3,4,2d,CC1=C(C2=CC=C(CNC(=O)[C@@H]3C[C@@H](O)CN3C(=O)...,3.5,2,2.900000,1020.210,896.016,0.276316,71.0,...,21.0,76.0,6.0,3.0,0.470588,3.0,12.0,7.70720,186.66,833.34
4,5,4a,CC1=NC(NC2=NC=C(C(=O)NC3=C(C)C=CC=C3Cl)S2)=CC(...,0.2,1,0.400000,1012.704,900.176,0.236842,70.0,...,18.0,76.0,7.0,3.0,0.460000,5.0,14.0,7.42946,214.98,785.02
5,6,2f,CC1(C)C(=O)N(C2=CC=C(C#N)C(C(F)(F)F)=C2)C(=S)N...,17.0,141,49.000000,837.830,697.696,0.265625,59.0,...,17.0,64.0,6.0,1.0,0.375000,1.0,12.0,4.40258,177.04,622.96
6,7,2b,CC1=C(C2=CC=C(CNC(=O)[C@@H]3C[C@@H](O)CN3C(=O)...,13.5,14,13.700000,1006.183,872.816,0.266667,70.0,...,20.0,75.0,6.0,3.0,0.460000,3.0,12.0,7.31710,186.66,813.34
7,8,2c,CC1=C(C2=CC=C(CNC(=O)[C@@H]3C[C@@H](O)CN3C(=O)...,2.6,4,3.200000,1128.150,931.232,0.256098,77.0,...,21.0,82.0,6.0,3.0,0.470588,3.0,12.0,8.44280,186.66,833.34
8,9,2a,CC1=C(C2=CC=C(CNC(=O)[C@@H]3C[C@@H](O)CN3C(=O)...,3.4,86,17.200000,1022.182,891.056,0.276316,71.0,...,21.0,76.0,6.0,3.0,0.460000,3.0,13.0,6.55350,195.89,804.11
9,10,2e,CC1=C(C2=CC=C(CNC(=O)[C@@H]3C[C@@H](O)CN3C(=O)...,0.6,3,1.300000,1078.143,902.096,0.253165,74.0,...,20.0,79.0,6.0,3.0,0.460000,3.0,12.0,7.80750,186.66,813.34
10,11,13a,CC1=CC=C(N2N=C3C(=O)N(CCCC(=O)NCCCCCCCCNC4=CC=...,3.7,128,21.800000,722.847,661.968,0.275862,53.0,...,16.0,58.0,6.0,1.0,0.435897,3.0,11.0,4.25776,177.39,602.61
11,12,3b,COC1=CC(C(=O)NCCOCCOCCOCCC(=O)NC2=CC=CC3=C2C(=...,10.0,170,41.200000,917.851,766.648,0.277778,66.0,...,20.0,72.0,7.0,1.0,0.340909,4.0,15.0,4.37840,242.78,637.22
12,13,3a,COC1=CC(C(=O)NCCOCCOCCOCC(=O)N[C@H](C(=O)N2C[C...,5.0,110,23.500000,1061.150,918.816,0.283951,75.0,...,23.0,81.0,7.0,3.0,0.423077,5.0,16.0,6.18942,241.76,798.24
13,14,10a,O=C1CCC(N2C(=O)C3=CC=CC(NCCOCCOCCOCCOCCOCCNC(=...,2.7,75,14.100000,1024.529,890.672,0.337500,73.0,...,27.0,80.0,8.0,1.0,0.411765,6.0,16.0,5.25320,262.76,757.24
14,15,7a,C[C@H]1CC2(CCN(C3=CC=C(C(=O)N4CCC(CN5CC6=CC7=C...,0.7,1,1.000000,788.349,695.408,0.092308,57.0,...,6.0,65.0,9.0,2.0,0.454545,1.0,9.0,5.36628,137.37,742.63
15,16,14a,CCOC1=CC(C(C)(C)C)=CC=C1C1=NC(C2=CC=C(Cl)C=C2)...,0.6,0,0.300000,1459.411,1291.704,0.236364,101.0,...,26.0,110.0,10.0,4.0,0.421053,2.0,13.0,12.29300,216.79,1303.21
16,17,12a,NC1=NC=NC2=C1C(C1=CC=C(OC3=CC=CC=C3)C=C1)=NN2[...,0.2,0,0.100000,775.826,669.592,0.136364,58.0,...,9.0,66.0,9.0,2.0,0.209302,3.0,12.0,5.35840,194.74,665.26
17,18,1c,CC1=C(C)C2=C(S1)N1C(C)=NN=C1[C@H](CC(=O)NCCCCC...,0.5,160,8.900000,903.934,790.896,0.235294,62.0,...,16.0,68.0,7.0,5.0,0.444444,3.0,12.0,7.77536,177.07,722.93
18,19,1a,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...,0.7,200,11.800000,1008.039,880.352,0.293333,69.0,...,22.0,75.0,7.0,5.0,0.489796,3.0,15.0,6.96328,204.76,775.24
19,20,1d,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...,0.7,110,8.800000,1070.736,942.000,0.283951,74.0,...,23.0,81.0,8.0,5.0,0.471698,3.0,17.0,7.74180,217.65,842.35
20,21,1f,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...,0.6,75,6.700000,930.960,813.040,0.228571,64.0,...,16.0,70.0,7.0,5.0,0.434783,4.0,12.0,6.80128,196.94,723.06
21,22,1g,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...,0.6,60,6.000000,991.012,861.040,0.270270,68.0,...,20.0,74.0,7.0,5.0,0.458333,4.0,14.0,6.05428,215.40,744.60
22,23,1h,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...,0.4,55,4.700000,1035.065,905.000,0.298701,71.0,...,23.0,77.0,7.0,5.0,0.480000,4.0,15.0,6.07088,224.63,775.37
23,24,1i,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...,0.8,20,4.000000,993.657,871.816,0.223684,69.0,...,17.0,76.0,8.0,5.0,0.420000,4.0,14.0,7.57980,209.83,790.17
24,25,1j,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...,0.7,22,3.900000,1053.709,924.808,0.262500,73.0,...,21.0,80.0,8.0,5.0,0.442308,4.0,16.0,6.83280,228.29,811.71
25,26,1k,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...,0.8,18,3.800000,1097.762,961.800,0.289157,76.0,...,24.0,83.0,8.0,5.0,0.462963,4.0,17.0,6.84940,237.52,842.48
26,27,1e,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...,0.6,89,7.300000,1050.705,921.320,0.250000,73.0,...,20.0,80.0,8.0,5.0,0.433962,3.0,16.0,7.40608,208.42,851.58
27,28,11a,O=C1CCC(N2CC3=C(SCCCCCCN4CCN(C5CCN(C6=NC=C(C(=...,1.1,10,3.400000,890.458,768.752,0.231884,62.0,...,16.0,69.0,8.0,1.0,0.454545,3.0,11.0,6.59200,156.10,723.90
28,29,5a,CNC1=NC(NC2=CC=C(C(=O)N3CCN(C[C@H]4CC[C@H](CSC...,7.4,14,10.300000,1019.711,903.008,0.233766,70.0,...,18.0,77.0,8.0,3.0,0.540000,5.0,14.0,6.69692,194.25,805.75
29,30,9a,CN(C1=CC=CC=C1CNC1=NC(NC2=CC=C(N3CCN(CCCCCCC(=...,2.4,4,3.200000,962.069,832.720,0.270270,68.0,...,20.0,74.0,7.0,1.0,0.413043,5.0,14.0,4.94890,218.38,701.62
30,31,8a,CNC(=O)C1=CC=CC=C1NC1=NC(NC2=CC=C(N3CCN(CCCCC(...,14.0,47,25.700000,823.311,712.712,0.215385,59.0,...,14.0,65.0,7.0,1.0,0.317073,5.0,13.0,4.31760,207.30,612.70
31,32,1b,CC1=C(C2=CC=C(CNC(=O)[C@@H]3C[C@@H](O)CN3C(=O)...,1.1,90,9.900000,1002.661,881.352,0.266667,69.0,...,20.0,75.0,7.0,4.0,0.469388,4.0,15.0,5.59668,211.49,768.51

In [112]:
dataset_1['P_app'] = dataset_2['P_app']
dataset_1['Smiles'] = dataset_2['Smiles']

In [113]:
dataset_1

,Molecular Weight (MW),CharVol (characteristic volume),Flexibility (number of rotatable bonds / number of bonds),Number of Heavy Atoms (HA),RingAtoms,Halogens,HeteroAtoms,RotBonds (NRotB),AllBonds,RingCount,...,Hydrogen Bond Acceptors (HBA),cLogD^7.4,Topological polar surface area (TPSA),Total non-polar surface area (TNSA),Ensemble_Average_PSA_Chloroform_ANI,Ensemble_Average_Num_IMHB_Chloroform_ANI,Ensemble_Average_RadiusOfGyration_Chloroform_ANI,P_appLog,P_app,Smiles
0,896.999,803.360,0.253521,65,42,0,19,18,71,7,...,14,2.64400,209.98,710.02,193.71,0.97,5.68,1.491362,31.016125,O=C(C(N1C(C2=CC=CC(NCCOCCOCCOCCC(N(CC3)CCN3C(C...
1,852.902,743.496,0.191176,62,42,0,19,13,68,7,...,13,1.76390,217.82,642.18,252.14,0.87,5.24,1.049218,11.171392,O=C(C(N1C(C2=CC=CC(NC(COCCOCC(N(CC3)CCN3C(C=C4...
2,850.930,753.592,0.191176,62,42,0,18,13,68,7,...,12,2.45750,208.59,671.41,248.01,0.67,5.47,0.812913,6.480741,O=C(C(N1C(C2=CC=CC(OCC(NCCCCC(N(CC3)CCN3C(C=C4...
3,1020.210,896.016,0.276316,71,33,3,20,21,76,6,...,12,7.70720,186.66,833.34,186.01,0.60,5.84,0.462398,2.900000,CC1=C(C2=CC=C(CNC(=O)[C@@H]3C[C@@H](O)CN3C(=O)...
4,1012.704,900.176,0.236842,70,39,1,20,18,76,7,...,14,7.42946,214.98,785.02,105.63,2.92,5.60,-0.397940,0.400000,CC1=NC(NC2=NC=C(C(=O)NC3=C(C)C=CC=C3Cl)S2)=CC(...
5,837.830,697.696,0.265625,59,34,3,19,17,64,6,...,12,4.40258,177.04,622.96,204.17,0.29,5.23,1.690196,49.000000,CC1(C)C(=O)N(C2=CC=C(C#N)C(C(F)(F)F)=C2)C(=S)N...
6,1006.183,872.816,0.266667,70,33,3,20,20,75,6,...,12,7.31710,186.66,813.34,175.16,0.32,5.41,1.136721,13.700000,CC1=C(C2=CC=C(CNC(=O)[C@@H]3C[C@@H](O)CN3C(=O)...
7,1128.150,931.232,0.256098,77,33,9,26,21,82,6,...,12,8.44280,186.66,833.34,160.07,0.93,5.93,0.505150,3.200000,CC1=C(C2=CC=C(CNC(=O)[C@@H]3C[C@@H](O)CN3C(=O)...
8,1022.182,891.056,0.276316,71,33,3,21,21,76,6,...,13,6.55350,195.89,804.11,197.66,1.64,5.16,1.235528,17.200000,CC1=C(C2=CC=C(CNC(=O)[C@@H]3C[C@@H](O)CN3C(=O)...
9,1078.143,902.096,0.253165,74,33,7,24,20,79,6,...,12,7.80750,186.66,813.34,217.11,0.00,5.63,0.113943,1.300000,CC1=C(C2=CC=C(CNC(=O)[C@@H]3C[C@@H](O)CN3C(=O)...
10,722.847,661.968,0.275862,53,34,0,14,16,58,6,...,11,4.25776,177.39,602.61,174.83,2.03,4.64,1.338456,21.800000,CC1=CC=C(N2N=C3C(=O)N(CCCC(=O)NCCCCCCCCNC4=CC=...
11,917.851,766.648,0.277778,66,40,3,22,20,72,7,...,15,4.37840,242.78,637.22,243.14,1.81,5.07,1.614897,41.200000,COC1=CC(C(=O)NCCOCCOCCOCCC(=O)NC2=CC=CC3=C2C(=...
12,1061.150,918.816,0.283951,75,39,3,23,23,81,7,...,16,6.18942,241.76,798.24,155.46,3.16,5.39,1.371068,23.500000,COC1=CC(C(=O)NCCOCCOCCOCC(=O)N[C@H](C(=O)N2C[C...
13,1024.529,890.672,0.337500,73,46,1,22,27,80,8,...,16,5.25320,262.76,757.24,241.95,3.00,5.42,1.149219,14.100000,O=C1CCC(N2C(=O)C3=CC=CC(NCCOCCOCCOCCOCCOCCNC(=...
14,788.349,695.408,0.092308,57,51,1,13,6,65,9,...,9,5.36628,137.37,742.63,261.21,0.00,8.77,0.000000,1.000000,C[C@H]1CC2(CCN(C3=CC=C(C(=O)N4CCC(CN5CC6=CC7=C...
15,1459.411,1291.704,0.236364,101,58,4,25,26,110,10,...,13,12.29300,216.79,1303.21,119.69,2.38,6.70,-0.522879,0.300000,CCOC1=CC(C(C)(C)C)=CC=C1C1=NC(C2=CC=C(Cl)C=C2)...
16,775.826,669.592,0.136364,58,52,0,15,9,66,9,...,12,5.35840,194.74,665.26,301.96,0.00,8.70,-1.000000,0.100000,NC1=NC=NC2=C1C(C1=CC=C(OC3=CC=CC=C3)C=C1)=NN2[...
17,903.934,790.896,0.235294,62,39,2,17,16,68,7,...,12,7.77536,177.07,722.93,149.92,2.01,4.97,0.949390,8.900000,CC1=C(C)C2=C(S1)N1C(C)=NN=C1[C@H](CC(=O)NCCCCC...
18,1008.039,880.352,0.293333,69,39,2,20,22,75,7,...,15,6.96328,204.76,775.24,161.36,2.54,5.37,1.071882,11.800000,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...
19,1070.736,942.000,0.283951,74,44,1,21,23,81,8,...,17,7.74180,217.65,842.35,145.60,2.24,5.33,0.944483,8.800000,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...
20,930.960,813.040,0.228571,64,39,2,18,16,70,7,...,12,6.80128,196.94,723.06,134.68,3.02,5.20,0.826075,6.700000,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...
21,991.012,861.040,0.270270,68,39,2,20,20,74,7,...,14,6.05428,215.40,744.60,137.19,3.90,5.60,0.778151,6.000000,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...
22,1035.065,905.000,0.298701,71,39,2,21,23,77,7,...,15,6.07088,224.63,775.37,132.52,2.23,5.94,0.672098,4.700000,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...
23,993.657,871.816,0.223684,69,44,1,19,17,76,8,...,14,7.57980,209.83,790.17,134.46,3.97,5.43,0.602060,4.000000,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...
24,1053.709,924.808,0.262500,73,44,1,21,21,80,8,...,16,6.83280,228.29,811.71,201.37,2.62,5.71,0.591065,3.900000,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...
25,1097.762,961.800,0.289157,76,44,1,22,24,83,8,...,17,6.84940,237.52,842.48,189.50,3.83,5.28,0.579784,3.800000,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...
26,1050.705,921.320,0.250000,73,44,1,20,20,80,8,...,16,7.40608,208.42,851.58,170.24,2.48,5.45,0.863323,7.300000,CC1=NOC([C@H](C(=O)N2C[C@H](O)C[C@H]2C(=O)N[C@...
27,890.458,768.752,0.231884,62,46,3,18,16,69,8,...,11,6.59200,156.10,723.90,139.42,2.00,5.13,0.531479,3.400000,O=C1CCC(N2CC3=C(SCCCCCCN4CCN(C5CCN(C6=NC=C(C(=...
28,1019.711,903.008,0.233766,70,43,2,20,18,77,8,...,14,6.69692,194.25,805.75,174.10,3.00,5.32,1.012837,10.300000,CNC1=NC(NC2=CC=C(C(=O)N3CCN(C[C@H]4CC[C@H](CSC...
29,962.069,832.720,0.270270,68,41,3,22,20,74,7,...,14,4.94890,218.38,701.62,226.08,1.06,5.65,0.505150,3.200000,CN(C1=CC=CC=C1CNC1=NC(NC2=CC=C(N3CCN(CCCCCCC(=...
30,823.311,712.712,0.215385,59,41,1,18,14,65,7,...,13,4.31760,207.30,612.70,192.67,3.93,5.25,1.409933,25.700000,CNC(=O)C1=CC=CC=C1NC1=NC(NC2=CC=C(N3CCN(CCCCC(...
31,1002.661,881.352,0.266667,69,39,1,20,20,75,7,...,15,5.59668,211.49,768.51,131.56,2.00,5.32,0.995635,9.900000,CC1=C(C2=CC=C(CNC(=O)[C@@H]3C[C@@H](O)CN3C(=O)...

A) Splitting the dataset into compounds with two classes with low and high permeability evenly so each class has 16 compounds.

In [114]:
Permeable_cutoff = (7)
Low_label = 0
High_label = +1
Permeable_key_str = f'Permeability High({High_label:})/Low({Low_label:})'
dataset_1[Permeable_key_str] = [High_label if p > Permeable_cutoff else Low_label for p in dataset_1['P_app']]

Number_Permeable_High = np.sum(dataset_1[Permeable_key_str] == +1)
Number_Permeable_Low = np.sum(dataset_1[Permeable_key_str] == 0)

print("Key:",Permeable_key_str)

print("Number with high permeability (above {:.1f} nm/s): {:d}".format(Permeable_cutoff,Number_Permeable_High))
print("Number with low permeability (above {:.1f} nm/s): {:d}".format(Permeable_cutoff,Number_Permeable_Low))

print("")

dataset_1[['P_app', Permeable_key_str] ]

Key: Permeability High(1)/Low(0)
Number with high permeability (above 7.0 nm/s): 16
Number with low permeability (above 7.0 nm/s): 16

        P_app  Permeability High(1)/Low(0)
0   31.016125                            1
1   11.171392                            1
2    6.480741                            0
3    2.900000                            0
4    0.400000                            0
5   49.000000                            1
6   13.700000                            1
7    3.200000                            0
8   17.200000                            1
9    1.300000                            0
10  21.800000                            1
11  41.200000                            1
12  23.500000                            1
13  14.100000                            1
14   1.000000                            0
15   0.300000                            0
16   0.100000                            0
17   8.900000                            1
18  11.800000                            1
19   8.800000                            1
20   6.700000                            0
21   6.000000                            0
22   4.700000                            0
23   4.000000                            0
24   3.900000                            0
25   3.800000                            0
26   7.300000                            1
27   3.400000                            0
28  10.300000                            1
29   3.200000                            0
30  25.700000                            1
31   9.900000                            1

B) For all 32 compounds, visualize the 2D chemical structure using RDKit and the mols2grid package, and show their measured passive permeability in nm/s and their low/high permeability classifciation.

In [115]:
# the %%capture command will surpress output to screen
%%capture
import sys
IN_COLAB = 'google.colab' in sys.modules
if IN_COLAB:
    !pip install rdkit mols2grid

In [116]:
import mols2grid

In [117]:
dataset_1['P_app(nm/s)'] = dataset_1['P_app'].round(2)

In [118]:
# by passing the dataframe, and giving the column with the SMILES string, we can
# plot all molecules
# we can also add information to the figures by using the subset variable
mols2grid.display(dataset_1,smiles_col='Smiles',subset=["img", 'P_app(nm/s)' ,Permeable_key_str ])

C) Perform classifcation using random forest classification model using the following hyperparameters:

Number of tree: 100
Maximum depth of each tree: 2
Maximum number of features for each tree: 50% of the number of input features (rounded up if that number is a fraction)
You should perform the classification using 3 different feature set:

2D RDKit features
3D Ensemble features
Combined set of 2D and 3D features
For each case, perform cross validation (CV) using a CV strategy of your choice, and obtain the average and standard deviation of metrics that measure the performance, including:

Accuracy
Precision
Receiver Operating Characteristic Area Under the Curve (ROC AUC)
In your analysis and metrics, the high permeability class should be consider as the postive class.

In [119]:
import math
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_validate, StratifiedKFold, ShuffleSplit
from sklearn import metrics

In [120]:
features_2d = [
    'Molecular Weight (MW)',
    'CharVol (characteristic volume)',
    'Flexibility (number of rotatable bonds / number of bonds)',
    'Number of Heavy Atoms (HA)',
    'RingAtoms',
    'Halogens',
    'HeteroAtoms',
    'RotBonds (NRotB)',
    'AllBonds',
    'RingCount',
    'NumStereo',
    'Fraction of sp3 Carbon Atoms (FSP3)',
    'Hydrogen Bond Donors (HBD)',
    'Hydrogen Bond Acceptors (HBA)',
    'cLogD^7.4',
    'Topological polar surface area (TPSA)',
    'Total non-polar surface area (TNSA)'
]

features_3d = [
    'Ensemble_Average_PSA_Chloroform_ANI',
    'Ensemble_Average_Num_IMHB_Chloroform_ANI',
    'Ensemble_Average_RadiusOfGyration_Chloroform_ANI'
]

features_combined = features_2d + features_3d

For 2D-Features

In [ ]:
import math
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_validate, StratifiedKFold, ShuffleSplit
from sklearn import metrics

# Features and target
features = dataset_1[features_2d].values
target   = dataset_1[Permeable_key_str].values

# max_features = 50% rounded up
n_max_features = math.ceil(len(features_2d) * 0.5)
print(f"Number of 2D features: {len(features_2d)}")
print(f"max_features: {n_max_features}")

# Model
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=2,
    max_features=n_max_features,
    random_state=42
)

# Scoring
scoring = {
    'accuracy' : 'accuracy',
    'precision': metrics.make_scorer(metrics.precision_score, zero_division=np.nan),
    'roc_auc'  : 'roc_auc'
}

# CV strategies
NumSplits = 100
scores_fold   = cross_validate(model, features, target,
                                scoring=scoring,
                                cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42))

scores_random = cross_validate(model, features, target,
                                scoring=scoring,
                                cv=ShuffleSplit(n_splits=NumSplits, test_size=0.5))

# Print results
print("\n========== 2D RDKit Features ==========")
print("Accuracy")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(scores_fold['test_accuracy'].mean(),   scores_fold['test_accuracy'].std()))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(scores_random['test_accuracy'].mean(), scores_random['test_accuracy'].std()))

print("Precision")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(np.nanmean(scores_fold['test_precision']),   np.nanstd(scores_fold['test_precision'])))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(np.nanmean(scores_random['test_precision']), np.nanstd(scores_random['test_precision'])))

print("ROC AUC")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(scores_fold['test_roc_auc'].mean(),   scores_fold['test_roc_auc'].std()))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(scores_random['test_roc_auc'].mean(), scores_random['test_roc_auc'].std()))

Number of 2D features: 17
max_features: 9

For 3D-features

In [ ]:
# Features and target
features = dataset_1[features_3d].values
target   = dataset_1[Permeable_key_str].values

# max_features = 50% rounded up
n_max_features = math.ceil(len(features_3d) * 0.5)
print(f"Number of 3D features: {len(features_3d)}")
print(f"max_features: {n_max_features}")

# Model
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=2,
    max_features=n_max_features,
    random_state=42
)

# Scoring
scoring = {
    'accuracy' : 'accuracy',
    'precision': metrics.make_scorer(metrics.precision_score, zero_division=np.nan),
    'roc_auc'  : 'roc_auc'
}

# CV strategies
NumSplits = 100
scores_fold   = cross_validate(model, features, target,
                                scoring=scoring,
                                cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42))

scores_random = cross_validate(model, features, target,
                                scoring=scoring,
                                cv=ShuffleSplit(n_splits=NumSplits, test_size=0.5))

# Print results
print("\n========== 3D RDKit Features ==========")
print("Accuracy")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(scores_fold['test_accuracy'].mean(),   scores_fold['test_accuracy'].std()))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(scores_random['test_accuracy'].mean(), scores_random['test_accuracy'].std()))

print("Precision")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(np.nanmean(scores_fold['test_precision']),   np.nanstd(scores_fold['test_precision'])))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(np.nanmean(scores_random['test_precision']), np.nanstd(scores_random['test_precision'])))

print("ROC AUC")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(scores_fold['test_roc_auc'].mean(),   scores_fold['test_roc_auc'].std()))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(scores_random['test_roc_auc'].mean(), scores_random['test_roc_auc'].std()))

For 2D and 3D combined features

In [ ]:
# Features and target
features = dataset_1[features_combined].values
target   = dataset_1[Permeable_key_str].values

# max_features = 50% rounded up
n_max_features = math.ceil(len(features_combined) * 0.5)
print(f"Number of combined features: {len(features_combined)}")
print(f"max_features: {n_max_features}")

# Model
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=2,
    max_features=n_max_features,
    random_state=42
)

# Scoring
scoring = {
    'accuracy' : 'accuracy',
    'precision': metrics.make_scorer(metrics.precision_score, zero_division=np.nan),
    'roc_auc'  : 'roc_auc'
}

# CV strategies
NumSplits = 100
scores_fold   = cross_validate(model, features, target,
                                scoring=scoring,
                                cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42))

scores_random = cross_validate(model, features, target,
                                scoring=scoring,
                                cv=ShuffleSplit(n_splits=NumSplits, test_size=0.5))

# Print results
print("\n========== Combined RDKit Features ==========")
print("Accuracy")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(scores_fold['test_accuracy'].mean(),   scores_fold['test_accuracy'].std()))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(scores_random['test_accuracy'].mean(), scores_random['test_accuracy'].std()))

print("Precision")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(np.nanmean(scores_fold['test_precision']),   np.nanstd(scores_fold['test_precision'])))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(np.nanmean(scores_random['test_precision']), np.nanstd(scores_random['test_precision'])))

print("ROC AUC")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(scores_fold['test_roc_auc'].mean(),   scores_fold['test_roc_auc'].std()))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(scores_random['test_roc_auc'].mean(), scores_random['test_roc_auc'].std()))

The 3D ensembles features gives the best calculation result among three. The 3D ensemble features (PSA, IMHB, radius of gyration)
obtained from MD simulations are the most informative for
predicting passive permeability. This makes physical sense
because permeability depends on the 3D conformation and
dynamic behavior of the molecule in a membrane-like
environment, which the 2D RDKit descriptors cannot capture.

Interestingly, adding 2D features to the 3D features
(combined) actually slightly decreased performance compared
to 3D alone, suggesting the 2D features may add noise
rather than useful information for this small dataset of
32 compounds.

D) Optional
 Analysing a  𝑘  nearest neighbors classifer (i.e.,  𝑘  nearest neighbors vote) by using the default value of 5 neighbors.

For 2D- features

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

# Features and target
features = dataset_1[features_2d].values
target   = dataset_1[Permeable_key_str].values

# KNN model with StandardScaler
model = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("knn",    KNeighborsClassifier(n_neighbors=5))
])

# Scoring
scoring = {
    'accuracy' : 'accuracy',
    'precision': metrics.make_scorer(metrics.precision_score,
                                     pos_label=1,
                                     zero_division=np.nan),
    'roc_auc'  : 'roc_auc'
}

# CV strategies
NumSplits = 100
scores_fold   = cross_validate(model, features, target,
                                scoring=scoring,
                                cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42))

scores_random = cross_validate(model, features, target,
                                scoring=scoring,
                                cv=ShuffleSplit(n_splits=NumSplits, test_size=0.5))

# Print results
print("\n========== KNN - 2D RDKit Features ==========")
print("Accuracy")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(scores_fold['test_accuracy'].mean(),   scores_fold['test_accuracy'].std()))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(scores_random['test_accuracy'].mean(), scores_random['test_accuracy'].std()))

print("Precision")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(np.nanmean(scores_fold['test_precision']),   np.nanstd(scores_fold['test_precision'])))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(np.nanmean(scores_random['test_precision']), np.nanstd(scores_random['test_precision'])))

print("ROC AUC")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(scores_fold['test_roc_auc'].mean(),   scores_fold['test_roc_auc'].std()))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(scores_random['test_roc_auc'].mean(), scores_random['test_roc_auc'].std()))

For 3D- features

In [ ]:


# Features and target
features = dataset_1[features_3d].values
target   = dataset_1[Permeable_key_str].values

# KNN model with StandardScaler
model = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("knn",    KNeighborsClassifier(n_neighbors=5))
])

# Scoring
scoring = {
    'accuracy' : 'accuracy',
    'precision': metrics.make_scorer(metrics.precision_score,
                                     pos_label=1,
                                     zero_division=np.nan),
    'roc_auc'  : 'roc_auc'
}

# CV strategies
NumSplits = 100
scores_fold   = cross_validate(model, features, target,
                                scoring=scoring,
                                cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42))

scores_random = cross_validate(model, features, target,
                                scoring=scoring,
                                cv=ShuffleSplit(n_splits=NumSplits, test_size=0.5))

# Print results
print("\n========== KNN - 3D RDKit Features ==========")
print("Accuracy")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(scores_fold['test_accuracy'].mean(),   scores_fold['test_accuracy'].std()))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(scores_random['test_accuracy'].mean(), scores_random['test_accuracy'].std()))

print("Precision")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(np.nanmean(scores_fold['test_precision']),   np.nanstd(scores_fold['test_precision'])))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(np.nanmean(scores_random['test_precision']), np.nanstd(scores_random['test_precision'])))

print("ROC AUC")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(scores_fold['test_roc_auc'].mean(),   scores_fold['test_roc_auc'].std()))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(scores_random['test_roc_auc'].mean(), scores_random['test_roc_auc'].std()))

For 2D and 3D combined features.

In [ ]:


# Features and target
features = dataset_1[features_combined].values
target   = dataset_1[Permeable_key_str].values

# KNN model with StandardScaler
model = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("knn",    KNeighborsClassifier(n_neighbors=5))
])

# Scoring
scoring = {
    'accuracy' : 'accuracy',
    'precision': metrics.make_scorer(metrics.precision_score,
                                     pos_label=1,
                                     zero_division=np.nan),
    'roc_auc'  : 'roc_auc'
}

# CV strategies
NumSplits = 100
scores_fold   = cross_validate(model, features, target,
                                scoring=scoring,
                                cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42))

scores_random = cross_validate(model, features, target,
                                scoring=scoring,
                                cv=ShuffleSplit(n_splits=NumSplits, test_size=0.5))

# Print results
print("\n========== KNN - Combined RDKit Features ==========")
print("Accuracy")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(scores_fold['test_accuracy'].mean(),   scores_fold['test_accuracy'].std()))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(scores_random['test_accuracy'].mean(), scores_random['test_accuracy'].std()))

print("Precision")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(np.nanmean(scores_fold['test_precision']),   np.nanstd(scores_fold['test_precision'])))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(np.nanmean(scores_random['test_precision']), np.nanstd(scores_random['test_precision'])))

print("ROC AUC")
print("  5-Fold CV          : {:.3f} +/- {:.3f}".format(scores_fold['test_roc_auc'].mean(),   scores_fold['test_roc_auc'].std()))
print("  Random Splits(100) : {:.3f} +/- {:.3f}".format(scores_random['test_roc_auc'].mean(), scores_random['test_roc_auc'].std()))

In KNN , I cant get same result as in random forest. However,  3D- ensembles gives the best reult among three like as in random forest analyis.
If we compare both model the random forest ROU value is higher than KNN model. So for 32- compound data set random forest model seem work well.